[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200