[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://render.com/docs/web-services#port-binding"
  VITE_ENVIRONMENT = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200